name: 'fetch-and-update'

on:
  push:
    tags-ignore:
    - '*.*'
    branches:
    - master

  workflow_dispatch:

jobs:
  fetch-and-update:
    name: 'fetch policies'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          cd tools && pip install -r requirements.txt

      - name: Fetch policies
        env:
          TENCENT_SECRET_ID: ${{ secrets.TENCENT_SECRET_ID }}
          TENCENT_SECRET_KEY: ${{ secrets.TENCENT_SECRET_KEY }}
        run: |
          python tools/main.py --endpoint cam.na-ashburn.tencentcloudapi.com

          git status
          git diff
